// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using usuarioApi.Database;

#nullable disable

namespace usuarioApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310195316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("usuarioApi.Models.Chatbot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("model");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasJsonPropertyName("temperature");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chatbots");

                    b.HasAnnotation("Relational:JsonPropertyName", "chatbots");
                });

            modelBuilder.Entity("usuarioApi.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatbotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("userid");

                    b.HasKey("Id");

                    b.HasIndex("ChatbotId");

                    b.ToTable("Messages");

                    b.HasAnnotation("Relational:JsonPropertyName", "messages");
                });

            modelBuilder.Entity("usuarioApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("usuarioApi.Models.Chatbot", b =>
                {
                    b.HasOne("usuarioApi.Models.User", "User")
                        .WithMany("Chatbots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("usuarioApi.Models.Message", b =>
                {
                    b.HasOne("usuarioApi.Models.Chatbot", "Chatbot")
                        .WithMany("Messages")
                        .HasForeignKey("ChatbotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatbot");
                });

            modelBuilder.Entity("usuarioApi.Models.Chatbot", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("usuarioApi.Models.User", b =>
                {
                    b.Navigation("Chatbots");
                });
#pragma warning restore 612, 618
        }
    }
}
